name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: yolov

    steps:
      - name: Get Tag Name
        id: tag
        run: echo "value=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Get current date for Image Tag
        id: date
        run: echo "value=$(TZ='Asia/Shanghai' date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            YOLOV_VERSION=${{ steps.tag.outputs.value }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/relucyimages:yolov-${{ steps.date.outputs.value }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/relucyimages:yolov-${{ steps.tag.outputs.value }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/relucyimages:yolov-latest
      
      - name: Push Summary
        run: echo "### Build YOLOv ${{ steps.tag.outputs.value }} :rocket:" >> $GITHUB_STEP_SUMMARY
